apiVersion: v1
kind: Secret
metadata:
  name: application-secrets
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=   # "admin" base64 encoded
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW4=   # "admin" base64 encoded
  MONGO_DB: bXlhcHlkYg==                 # "myappdb" base64 encoded
